### PR TITLE
boost 1.67: fix android < 21 error where pthread_condattr_setclock is Called When Method is Only Avaliable in Android >= 21

### PR DESCRIPTION
**Pull request by epicstar**
See here: https://github.com/moritz-wundke/Boost-for-Android/issues/132

### CODE REVIEW

**Comment by Manromen** [comment]
Is there a reason why this isn't merged yet? With this patch I could successfully build all architectures.

**Comment by pelya** [comment]
The reason why this isn't merged yet is because project maintainers are
lazy.

**Comment by epicstar** [comment]
> The reason why this isn't merged yet is because project maintainers are
lazy.

Rekt...

**Comment by pelya** [comment]
Not tested in any way, I'm just a monkey pressing random buttons

**Pull request merged**
