### PR TITLE
added 22.0 version. seems to work on mac

### PR DESCRIPTION
**Pull request by AndrewBloom**
just added the ndk 22.0 on the build script and seems it compiled correctly on mac.

### CODE REVIEW

**Comment by moritz-wundke** [comment]
@AndrewBloom is this still valid or active in any sense?

**Comment by crroush** [comment]
@moritz-wundke at this point does it make sense to just check if the NDK_RN is >= 17.1?  It seems every subversion between 21.x and 23.x nothing is really changing but adding another line to that case statement.

**Comment by moritz-wundke** [comment]
> @moritz-wundke at this point does it make sense to just check if the NDK_RN is >= 17.1? It seems every subversion between 21.x and 23.x nothing is really changing but adding another line to that case statement.

Yeah I feel the same, while if we do that we should add a comment indicating it.

**Comment by pelya** [comment]
Not needed anymore

**Pull request closed without merging**
